api_target: api.textile.io:443
key: bafzbeiagzbglqm4ibz6hfd4v25kt2yjgjqhq3lq6fgpxmieiqibuhlnpum
log:
  debug: false
org: omoearthathackfs
project: omo-earth-test
thread: bafkssdo3y5iynunynncwm2vkddxvnzsfksuir6gd7yjsmg3rjbpyuii
