api_target: api.textile.io:443
key: bafzbeib4jumayxhcgcsu5xaqwtpglviwu7cjupwd6nbrao3j2cgi7czd5a
log:
  debug: false
org: omoearth-hackfs
project: omo-earth-test
thread: bafkqtcj3pzmu6tdjatgwvvooyco3f2z7oqvxntcm4ijf7eh4p2gyfdi
