name: "Textile Bucket - Deploy"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: push textile bucket
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - name: push # push to a known bucket
        id: bucket
        uses: textileio/github-action-buckets@v14
        with:
          key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
          secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
          bucket: "showcase"
          path: 'dist'
          thread: ${{ secrets.THREAD }}
      - run: echo "bucket - ${{ steps.bucket.outputs.key }}"
      - run: echo "ipfs - ${{ steps.bucket.outputs.ipfs }}"
      - run: echo "ipfs link - ${{ steps.bucket.outputs.ipfsUrl }}"
      - run: echo "ipns - ${{ steps.bucket.outputs.ipns }}"
      - run: echo "ipns link - ${{ steps.bucket.outputs.ipnsUrl }}"
      - run: echo "hub - ${{ steps.bucket.outputs.hub }}"
      - run: echo "www - ${{ steps.bucket.outputs.www }}"
